"""
Usage
-----------------
    uv run ./methods/optuna_studies/LA.py --jobs 8 --trials 100 --instance-idx 0
    uv run ./methods/optuna_studies/LA.py --jobs 8 --trials 100 --instance-idx 0 --max-wh 1000
"""

from __future__ import annotations

import argparse
import pickle
import re
from multiprocessing import cpu_count
from pathlib import Path
from typing import Any

import gymnasium as gym
import inventorygyms  # noqa: F401
import inventorygyms.wrappers.transhipment.lookahead as LA
import numpy as np
import optuna
import pandas as pd
from joblib import Parallel, delayed

# Number of Monte-Carlo replications per Optuna trial (higher = less noise, slower)
N_SIMS = 5000

STUDY_NAME = "inventory_tuning"
PROJECT_ROOT = Path(__file__).resolve().parents[2]
INSTANCES_PATH = PROJECT_ROOT / "parameters" / "instances.pkl"
RESULTS_DIR = PROJECT_ROOT / "results" / "LA"
MIN_WH_ONLINE_DEMAND_FACTOR = 0.90
MAX_WH_DEMAND_FACTOR = 1.25


# ---------------------------------------------------------------------------
# Instance helpers
# ---------------------------------------------------------------------------
def load_instance(instance_idx: int, instances_path: Path = INSTANCES_PATH) -> dict[str, Any]:
    """
    Load a single inventory instance from ``parameters/instances.pkl``.

    Parameters
    ----------
    instance_idx : int
        Index into the pickled instance list.
    instances_path : Path
        Path to the pickle generated by ``parameters/param_generator.py``.

    Returns
    -------
    dict[str, Any]
        Environment kwargs for ``inventorygyms/TwoEchelonPLSTS-v0``.

    Raises
    ------
    FileNotFoundError
        If the instance pickle does not exist.
    TypeError
        If the pickle is not a list of dictionaries.
    ValueError
        If ``instance_idx`` is outside the available range.
    """
    if not instances_path.exists():
        raise FileNotFoundError(
            f"Could not find {instances_path}. Generate it with parameters/param_generator.py first."
        )

    with instances_path.open("rb") as file:
        instances = pickle.load(file)

    if not isinstance(instances, list) or not all(isinstance(item, dict) for item in instances):
        raise TypeError(f"Expected {instances_path} to contain a list[dict].")

    if instance_idx < 0 or instance_idx >= len(instances):
        raise ValueError(f"Instance index {instance_idx} out of range [0, {len(instances) - 1}]")

    return instances[instance_idx]


def demand_totals(instance_params: dict[str, Any]) -> tuple[float, float, float]:
    """
    Calculate total expected store, online, and combined demand for an instance.

    Parameters
    ----------
    instance_params : dict[str, Any]
        Instance dictionary loaded from ``parameters/instances.pkl``.

    Returns
    -------
    tuple[float, float, float]
        Store demand total, online demand total, and combined total demand.

    Raises
    ------
    ValueError
        If required demand parameters are missing or total demand is not positive.
    """
    store_demand_params = instance_params.get("store_demand_params")
    online_demand_params = instance_params.get("online_demand_params")
    if store_demand_params is None or online_demand_params is None:
        raise ValueError(
            "Instance must contain store_demand_params and online_demand_params to infer "
            "warehouse bounds."
        )

    store_demand = float(np.sum(np.asarray(store_demand_params, dtype=float)))
    online_demand = float(np.sum(np.asarray(online_demand_params, dtype=float)))
    total_demand = store_demand + online_demand

    if total_demand <= 0:
        raise ValueError("Total store and online demand must be positive to infer warehouse bounds.")

    return store_demand, online_demand, total_demand


def infer_min_wh(
    instance_params: dict[str, Any],
    online_demand_factor: float = MIN_WH_ONLINE_DEMAND_FACTOR,
) -> int:
    """
    Infer the minimum warehouse order-up-to level from total expected online demand.

    Parameters
    ----------
    instance_params : dict[str, Any]
        Instance dictionary loaded from ``parameters/instances.pkl``.
    online_demand_factor : float
        Multiplier applied to total expected online demand. Values below 1 make the
        lower bound a bit less than total expected online demand.

    Returns
    -------
    int
        Minimum warehouse order-up-to level.

    Raises
    ------
    ValueError
        If ``online_demand_factor`` is outside ``(0, 1]``.
    """
    if online_demand_factor <= 0 or online_demand_factor > 1:
        raise ValueError("online_demand_factor must be in the interval (0, 1].")

    _, online_demand, _ = demand_totals(instance_params)
    return int(np.floor(online_demand * online_demand_factor))


def infer_max_wh(instance_params: dict[str, Any], demand_factor: float = MAX_WH_DEMAND_FACTOR) -> int:
    """
    Infer a warehouse order-up-to search ceiling from total expected demand.

    ``parameters/param_generator.py`` stores ``store_demand_params`` as one demand-rate
    trajectory per store and ``online_demand_params`` as one demand rate per period.
    The inferred ceiling is deliberately above total expected store + online demand,
    but bounded to a simple demand multiple so Optuna does not search implausibly huge values.

    Parameters
    ----------
    instance_params : dict[str, Any]
        Instance dictionary loaded from ``parameters/instances.pkl``.
    demand_factor : float
        Multiplier applied to total expected demand. Must be greater than 1.

    Returns
    -------
    int
        Inferred maximum warehouse order-up-to level.

    Raises
    ------
    ValueError
        If demand parameters are missing or ``demand_factor`` is not greater than 1.
    """
    if demand_factor <= 1:
        raise ValueError("demand_factor must be greater than 1.")

    _, _, total_demand = demand_totals(instance_params)
    return int(np.ceil(total_demand * demand_factor))


def instance_summary(
    instance_idx: int,
    instance_params: dict[str, Any],
    min_wh: int,
    max_wh: int,
) -> dict[str, Any]:
    """
    Build metadata describing the instance and chosen warehouse search bound.

    Parameters
    ----------
    instance_idx : int
        Index of the selected instance in ``parameters/instances.pkl``.
    instance_params : dict[str, Any]
        Selected instance configuration.
    min_wh : int
        Minimum warehouse order-up-to level used by Optuna.
    max_wh : int
        Maximum warehouse order-up-to level used by Optuna.

    Returns
    -------
    dict[str, Any]
        Flat metadata suitable for adding to a CSV of trial results.
    """
    store_demand, online_demand, total_demand = demand_totals(instance_params)

    return {
        "instance_idx": instance_idx,
        "trajectory": instance_params.get("trajectory", instance_params.get("trajectory\"")),
        "stores": instance_params.get("stores"),
        "periods": instance_params.get("periods"),
        "cluster_method": instance_params.get("cluster_method"),
        "dfw_chance": instance_params.get("dfw_chance"),
        "holding_warehouse": instance_params.get("holding_warehouse"),
        "holding_store": instance_params.get("holding_store"),
        "penalty": instance_params.get("penalty"),
        "store_demand_total": store_demand,
        "online_demand_total": online_demand,
        "total_demand": total_demand,
        "min_wh": min_wh,
        "max_wh": max_wh,
    }


def build_output_path(output_dir: Path, study_name: str, instance_idx: int) -> Path:
    """
    Build a deterministic CSV path for a study result.

    Parameters
    ----------
    output_dir : Path
        Directory where the CSV should be written.
    study_name : str
        Optuna study name.
    instance_idx : int
        Selected instance index.

    Returns
    -------
    Path
        CSV output path.
    """
    safe_study_name = re.sub(r"[^A-Za-z0-9_.-]+", "_", study_name).strip("_")
    return output_dir / f"instance_{instance_idx}_{safe_study_name}.csv"


# ---------------------------------------------------------------------------
# Simulation runner
# ---------------------------------------------------------------------------
def _as_pipeline_inventory(value: Any, pipeline_length: int) -> list[float]:
    """
    Convert a scalar initial inventory value into the pipeline format expected by the env.

    ``TwoEchelonPLSTS.__init__`` expects each warehouse/store initial inventory entry to be a
    sequence whose length is the relevant lead time plus one. Existing instances generated by
    ``parameters/param_generator.py`` store scalar starting inventory values instead.
    """
    if isinstance(value, list | tuple | np.ndarray):
        return [float(item) for item in value]

    return [float(value), *([0.0] * (pipeline_length - 1))]


def _normalise_initial_inventory(instance: dict[str, Any]) -> list[list[float]]:
    """
    Return initial inventory in the format expected by ``TwoEchelonPLSTS.__init__``.

    The environment expects ``[warehouse_pipeline, store_1_pipeline, ...]``. Each pipeline has
    length ``lead_time + 1``. The instances currently saved by ``parameters/param_generator.py``
    contain scalar values, and for stores omit the final store, so this reconstructs store
    starting inventory from the first period of ``store_demand_params`` when required.
    """
    lead_time = instance.get("lead_time", [1, 1, 0])
    warehouse_pipeline_length = int(lead_time[0]) + 1
    store_pipeline_length = int(lead_time[1]) + 1
    stores = int(instance["stores"])
    initial_inventory = instance.get("initial_inventory", [])

    if (
        isinstance(initial_inventory, list)
        and len(initial_inventory) == stores + 1
        and all(isinstance(item, list | tuple | np.ndarray) for item in initial_inventory)
    ):
        return [
            _as_pipeline_inventory(initial_inventory[0], warehouse_pipeline_length),
            *[
                _as_pipeline_inventory(store_inventory, store_pipeline_length)
                for store_inventory in initial_inventory[1:]
            ],
        ]

    store_demand_params = instance.get("store_demand_params")
    if store_demand_params is None:
        raise ValueError("store_demand_params is required to normalise initial_inventory.")

    store_initial_inventory = [float(store_demand[0]) for store_demand in store_demand_params]
    if initial_inventory:
        warehouse_initial_inventory = initial_inventory[0]
    else:
        online_demand_params = instance.get("online_demand_params", [0.0])
        warehouse_initial_inventory = float(online_demand_params[0]) + sum(store_initial_inventory)

    return [
        _as_pipeline_inventory(warehouse_initial_inventory, warehouse_pipeline_length),
        *[
            _as_pipeline_inventory(store_inventory, store_pipeline_length)
            for store_inventory in store_initial_inventory
        ],
    ]


def _environment_params(instance: dict[str, Any]) -> dict[str, Any]:
    """
    Return only the fields accepted by ``TwoEchelonPLSTS.__init__``.

    ``parameters/instances.pkl`` may include metadata such as ``trajectory`` and
    ``cluster_method`` for downstream analysis. Those fields should be retained
    for reporting but must not be forwarded to ``gym.make``.
    """
    metadata_keys = {"trajectory", "trajectory\"", "cluster_method"}
    env_params = {key: value for key, value in instance.items() if key not in metadata_keys}
    env_params["initial_inventory"] = _normalise_initial_inventory(instance)
    return env_params


def _create_env(instance: dict[str, Any]) -> LA.ts_la:
    """Create a fresh wrapped environment (safe for multiprocessing)."""
    env = gym.make("inventorygyms/TwoEchelonPLSTS-v0", **_environment_params(instance))
    wrapped_env = LA.ts_la(env)
    wrapped_env.reset()
    return wrapped_env


def run_simulation(instance: dict[str, Any], warehouse_order_up_to: int, seed: int = 42) -> float:
    """
    Run N_SIMS replications of the DES and return the mean total cost.

    Parameters
    ----------
    instance : dict[str, Any]
        Environment kwargs forwarded to ``gym.make``.
    warehouse_order_up_to : int
        The warehouse replenishment target passed to ``generate_action``.
    seed : int
        RNG seed for reproducibility.

    Returns
    -------
    float
        Mean total cost per replication. Lower is better.
    """
    wrapped_env = _create_env(instance)
    wrapped_env.reset(seed=seed)

    all_period_costs: list[float] = []

    for _ in range(N_SIMS):
        sim_costs = []
        terminated = False
        while not terminated:
            action = wrapped_env.generate_action(warehouse_order_up_to, True, "RegBS")
            _, reward, terminated, _, _ = wrapped_env.step(action)
            sim_costs.append(-reward)
        all_period_costs.append(float(np.sum(sim_costs)))
        wrapped_env.reset()

    return float(np.mean(all_period_costs))


# ---------------------------------------------------------------------------
# Optuna objective
# ---------------------------------------------------------------------------
def objective(trial: optuna.Trial, instance_params: dict[str, Any], max_wh: int) -> float:
    """
    Optuna objective function for the Lookahead policy.

    Parameters
    ----------
    trial : optuna.Trial
        Optuna trial object.
    instance_params : dict[str, Any]
        Instance configuration dictionary.
    max_wh : int
        Maximum warehouse order-up-to level to trial.

    Returns
    -------
    float
        Mean total cost per replication.
    """
    warehouse_order_up_to = trial.suggest_int("warehouse_order_up_to", 0, max_wh)
    return run_simulation(instance_params, warehouse_order_up_to, seed=trial.number)


# ---------------------------------------------------------------------------
# Parallel trial executor (module-level for pickling with joblib)
# ---------------------------------------------------------------------------
def run_replication_chunk(
    chunk_id: int,
    warehouse_order_up_to: int,
    instance_params: dict[str, Any],
    trial_seed: int,
    chunk_size: int,
    n_sims: int,
) -> list[float]:
    """
    Run a chunk of Monte Carlo replications in parallel.

    This must be at module level (not nested) to be picklable by joblib.

    Parameters
    ----------
    chunk_id : int
        Which chunk (0, 1, 2, ...) to identify which replications to run.
    warehouse_order_up_to : int
        Parameter value for this trial.
    instance_params : dict[str, Any]
        Instance configuration.
    trial_seed : int
        Base seed for reproducibility.
    chunk_size : int
        Number of replications per chunk.
    n_sims : int
        Total replications, used to size the final chunk correctly.

    Returns
    -------
    list[float]
        Total costs for each replication in this chunk.
    """
    costs = []
    env = _create_env(instance_params)
    n_full_chunks = n_sims // chunk_size
    n_reps = chunk_size if chunk_id < n_full_chunks else n_sims - (chunk_id * chunk_size)

    if n_reps <= 0:
        return costs

    env.reset(seed=trial_seed + chunk_id)
    for _ in range(n_reps):
        sim_costs = []
        terminated = False
        while not terminated:
            action = env.generate_action(warehouse_order_up_to, True, "RegBS")
            _, reward, terminated, _, _ = env.step(action)
            sim_costs.append(-reward)
        costs.append(float(np.sum(sim_costs)))
        env.reset()

    return costs


# ---------------------------------------------------------------------------
# Study entry-point
# ---------------------------------------------------------------------------
def run_study(
    n_trials: int = 50,
    n_jobs: int = 1,
    study_name: str = STUDY_NAME,
    instance_params: dict[str, Any] | None = None,
    min_wh: int = 0,
    max_wh: int = 50,
) -> optuna.Study:
    """
    Create and run an Optuna study with joblib multiprocessing.

    Strategy:
    - Optuna's TPE sampler suggests parameter values.
    - Each parameter suggestion is evaluated by parallelising Monte Carlo replications.
    - Optuna itself runs sequentially to avoid nested multiprocessing contention.

    Parameters
    ----------
    n_trials : int
        Total number of Optuna trials to run.
    n_jobs : int
        Number of parallel processes for replications. Use ``-1`` for all cores.
    study_name : str
        Human-readable name for the study.
    instance_params : dict[str, Any] | None
        Instance configuration dictionary.
    min_wh : int
        Minimum warehouse order-up-to level to trial.
    max_wh : int
        Maximum warehouse order-up-to level to trial.

    Returns
    -------
    optuna.Study
        The completed study.

    Raises
    ------
    ValueError
        If ``instance_params`` is missing or warehouse bounds are invalid.
    """
    if instance_params is None:
        raise ValueError("instance_params must be provided.")
    if min_wh < 0:
        raise ValueError("min_wh must be non-negative.")
    if max_wh <= min_wh:
        raise ValueError("max_wh must be greater than min_wh.")

    optuna.logging.set_verbosity(optuna.logging.WARNING)

    sampler = optuna.samplers.TPESampler(seed=42)
    study = optuna.create_study(
        direction="minimize",
        study_name=study_name,
        sampler=sampler,
    )

    effective_jobs = cpu_count() if n_jobs == -1 else n_jobs
    effective_jobs = max(1, min(effective_jobs, N_SIMS))

    print(f"Running {n_trials} trials")
    print(f"Warehouse order-up-to search range: [{min_wh}, {max_wh}]")
    print(f"Parallelising {N_SIMS} replications per trial across {effective_jobs} processes")

    def parallel_objective(trial: optuna.Trial) -> float:
        """
        Objective function: Optuna controls trial parameters,
        we parallelise replication sampling with joblib.
        """
        warehouse_order_up_to = trial.suggest_int("warehouse_order_up_to", min_wh, max_wh)


        if effective_jobs == 1:
            return run_simulation(instance_params, warehouse_order_up_to, seed=trial.number)

        chunk_size = int(np.ceil(N_SIMS / effective_jobs))
        n_chunks = int(np.ceil(N_SIMS / chunk_size))

        replication_results = Parallel(
            n_jobs=effective_jobs,
            backend="multiprocessing",
        )(
            delayed(run_replication_chunk)(
                chunk_id=i,
                warehouse_order_up_to=warehouse_order_up_to,
                instance_params=instance_params,
                trial_seed=trial.number,
                chunk_size=chunk_size,
                n_sims=N_SIMS,
            )
            for i in range(n_chunks)
        )

        all_costs = [cost for chunk in replication_results for cost in chunk]
        return float(np.mean(all_costs))

    param_counts: dict[int, int] = {}

    def convergence_tracking_callback(study: optuna.Study, trial: optuna.Trial) -> None:
        """Track repeated parameter suggestions to detect convergence."""
        if trial.state != optuna.trial.TrialState.COMPLETE:
            return

        param_value = trial.params.get("warehouse_order_up_to")
        if param_value is None:
            return

        param_counts[param_value] = param_counts.get(param_value, 0) + 1
        count = param_counts[param_value]

        if count == 2:
            print(
                "\n[Convergence] Parameter "
                f"warehouse_order_up_to={param_value} suggested again (2nd time)"
            )
        elif count > 2 and count % 5 == 0:
            print(
                f"[Convergence] Parameter warehouse_order_up_to={param_value} "
                f"suggested {count} times"
            )

        if count == 10:
            print(
                "\n[Convergence] Parameter "
                f"warehouse_order_up_to={param_value} suggested 10 times. Stopping study."
            )
            study.stop()

    study.optimize(
        parallel_objective,
        n_trials=n_trials,
        gc_after_trial=True,
        n_jobs=1,
        callbacks=[convergence_tracking_callback],
    )

    return study


# ---------------------------------------------------------------------------
# Reporting helpers
# ---------------------------------------------------------------------------
def print_study_summary(study: optuna.Study) -> None:
    """Print the best result and number of completed trials."""
    print("\n=== Optuna Study Summary ===")
    print(f"  Best value  : {study.best_value:.4f}  (mean total cost)")
    print(f"  Best params : {study.best_params}")
    print(f"  Trials run  : {len(study.trials)}")


def trials_to_dataframe(
    study: optuna.Study,
    metadata: dict[str, Any] | None = None,
) -> pd.DataFrame:
    """
    Return all completed trials as a tidy DataFrame.

    Parameters
    ----------
    study : optuna.Study
        Completed Optuna study.
    metadata : dict[str, Any] | None
        Optional flat metadata to add to every row.

    Returns
    -------
    pd.DataFrame
        Trial results sorted by objective value.
    """
    rows = []
    for trial in study.trials:
        if trial.state == optuna.trial.TrialState.COMPLETE:
            row = {
                "trial": trial.number,
                "mean_total_cost": trial.value,
                **trial.params,
            }
            if metadata is not None:
                row = {**metadata, **row}
            rows.append(row)

    columns = ["min_wh", "max_wh", "trial", "mean_total_cost", "warehouse_order_up_to"]
    return pd.DataFrame(rows).loc[:, columns].sort_values("mean_total_cost").reset_index(drop=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run Optuna inventory tuning study with joblib multiprocessing"
    )
    parser.add_argument("--trials", type=int, default=50, help="Total number of trials to run")
    parser.add_argument(
        "--jobs",
        type=int,
        default=1,
        help="Parallel processes for joblib (1 = sequential, -1 = all cores)",
    )
    parser.add_argument("--study", type=str, default=STUDY_NAME, help="Study name")
    parser.add_argument(
        "--instance-idx",
        type=int,
        required=True,
        help="Index of the instance to load from parameters/instances.pkl",
    )
    parser.add_argument(
        "--max-wh",
        "--max_wh",
        dest="max_wh",
        type=int,
        default=None,
        help=(
            "Max warehouse order-up-to level to trial. If omitted, this is inferred as "
            f"ceil((total store demand + total online demand) * {MAX_WH_DEMAND_FACTOR})."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=RESULTS_DIR,
        help="Directory where trial-level CSV results should be saved",
    )
    args = parser.parse_args()

    instance_params = load_instance(args.instance_idx)
    min_wh = infer_min_wh(instance_params)
    max_wh = args.max_wh if args.max_wh is not None else infer_max_wh(instance_params)
    instance_params = {
        **instance_params,
        "warehouse_capacity": max(int(instance_params.get("warehouse_capacity", 0)), max_wh),
    }
    metadata = instance_summary(args.instance_idx, instance_params, min_wh, max_wh)

    print(f"Loaded instance {args.instance_idx} from {INSTANCES_PATH}")
    print(
        "Demand totals: "
        f"stores={metadata['store_demand_total']:.2f}, "
        f"online={metadata['online_demand_total']:.2f}, "
        f"combined={metadata['total_demand']:.2f}"
    )

    study = run_study(
        n_trials=args.trials,
        n_jobs=args.jobs,
        study_name=args.study,
        instance_params=instance_params,
        min_wh=min_wh,
        max_wh=max_wh,
    )

    print_study_summary(study)

    df = trials_to_dataframe(study, metadata=metadata)
    print("\nTop 5 trial results:")
    print(df.head(5))

    args.output_dir.mkdir(parents=True, exist_ok=True)
    output_path = build_output_path(args.output_dir, args.study, args.instance_idx)
    df.to_csv(output_path, index=False)
    print(f"Saved trial results to {output_path}")
